config/routes.rb
WeightedDemocracy::Application.routes.draw do
  root :to => 'issues#index'

  resources :users

  resources :issues

  resources :disciplines do
    resources :questions
  end
    
  resources :questions do
    #/questions/1/answers maps to answers#index
    resources :answers
  end

  match '/login' => 'sessions#new', :as => 'login', :via => :get
  match '/login' => 'sessions#create', :as => 'login', :via => :post
  match '/logout' => 'sessions#destroy', :as => 'logout' 
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :discipline
  has_many :answers
  attr_accessible :name, :text, :discipline_id
  validates_presence_of :name
  validates_presence_of :text
  
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  # GET /questions
  # GET /questions.json
  before_filter :ensure_discipline

  def ensure_discipline
    @discipline = Discipline.find_by_id(params[:discipline_id])
    if !@discipline
      redirect_to disciplines_path
    end
  end

  def index
    @questions = @discipline.questions

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @questions }
    end
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    @question = @discipline.questions.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @question }
    end
  end

  # GET /questions/new
  # GET /questions/new.json
  def new
    @question = @discipline.questions.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @question }
    end
  end

  # GET /questions/1/edit
  def edit
    @question = @discipline.questions.find(params[:id])
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = @discipline.questions.new(params[:question])
    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render json: @question, status: :created, location: @question }
      else
        format.html { render action: "new" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /questions/1
  # PUT /questions/1.json
  def update
    @question = Question.find(params[:id])

    respond_to do |format|
      if @question.update_attributes(params[:question])
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question = Question.find(params[:id])
    @question.destroy

    respond_to do |format|
      format.html { redirect_to questions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.haml
= form_for @question do |f|
  - if @question.errors.any?
    #error_explanation
      %h2= "#{pluralize(@question.errors.count, "error")} prohibited this question from being saved:"
      %ul
        - @question.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :text
    = f.text_area :text
  .field
    = f.label :discipline_id
    = f.number_field :discipline_id
  .actions
    = f.submit 'Save'

app/views/questions/edit.html.haml
%h1 Editing question

= render 'form'

= link_to 'Show', @question
\|
= link_to 'Back', questions_path

app/views/questions/index.html.haml
%h1 Listing questions

%table
  %tr
    %th Name
    %th Text
    %th
    %th
    %th

  - @questions.each do |question|
    %tr
      %td= link_to question.name, edit_question_path(question)
      %td= question.text
      %td= link_to 'Show', question
      %td= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Question', new_question_path

app/views/questions/new.html.haml
%h1 New question

= render 'form'

= link_to 'Back', questions_path

app/views/questions/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @question.name
%p
  %b Text:
  = @question.text
%table
  %tr
    %th Answers
    %th= link_to 'New Answer', new_question_answer_path(@question)
  - @question.answers.each do |answer|
    %tr
      %td= answer.text
      %td= link_to 'Edit', edit_question_answer_path(@question)

= link_to 'Edit', edit_question_path(@question)
\|
= link_to 'Back', discipline_path(@discipline)