config/routes.rb
WeightedDemocracy::Application.routes.draw do
  root :to => 'issues#index'

  resources :users

  resources :issues

  resources :disciplines do
    resources :questions
  end
    
  resources :questions do
    #/questions/1/answers maps to answers#index
    resources :answers
  end

  match '/login' => 'sessions#new', :as => 'login', :via => :get
  match '/login' => 'sessions#create', :as => 'login', :via => :post
  match '/logout' => 'sessions#destroy', :as => 'logout' 
end

app/models/discipline.rb
class Discipline < ActiveRecord::Base
  attr_accessible :description, :name, :issue_id
  validates_presence_of :name
  validates_presence_of :description

  has_many :questions
  has_many :issue_disciplines
  has_many :issues, :through => :issue_disciplines
end

app/controllers/disciplines_controller.rb
class DisciplinesController < ApplicationController
  def index
    @disciplines = Discipline.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @disciplines }
    end
  end

  def show
    @discipline = Discipline.find(params[:id])
    session[:discipline_id] = @discipline.id
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @discipline }
    end
  end

  def new
    @discipline = Discipline.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @discipline }
    end
  end

  def edit
    @discipline = Discipline.find(params[:id])
  end

  def create
    @discipline = Discipline.new(params[:discipline])

    respond_to do |format|
      if @discipline.save
        format.html { redirect_to @discipline, notice: 'Discipline was successfully created.' }
        format.json { render json: @discipline, status: :created, location: @discipline }
      else
        format.html { render action: "new" }
        format.json { render json: @discipline.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @discipline = Discipline.find(params[:id])

    respond_to do |format|
      if @discipline.update_attributes(params[:discipline])
        format.html { redirect_to @discipline, notice: 'Discipline was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @discipline.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @discipline = Discipline.find(params[:id])
    @discipline.destroy

    respond_to do |format|
      format.html { redirect_to disciplines_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/disciplines_helper.rb
module DisciplinesHelper
end

app/views/disciplines/_form.html.haml
= form_for @discipline do |f|
  - if @discipline.errors.any?
    #error_explanation
      %h2= "#{pluralize(@discipline.errors.count, "error")} prohibited this discipline from being saved:"
      %ul
        - @discipline.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_area :description
  .actions
    = f.submit 'Save'

app/views/disciplines/edit.html.haml
%h1 Editing discipline

= render 'form'

= link_to 'Show', @discipline
\|
= link_to 'Back', disciplines_path

app/views/disciplines/index.html.haml
%h1 Listing disciplines

%table
  %tr
    %th Name
    %th Description
    %th
    %th
    %th

  - @disciplines.each do |discipline|
    %tr
      %td= link_to discipline.name, discipline
      %td= discipline.description
      %td= link_to 'Edit', edit_discipline_path(discipline)
      %td= link_to 'Destroy', discipline, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Discipline', new_discipline_path

app/views/disciplines/new.html.haml
%h1 New discipline

= render 'form'

= link_to 'Back', disciplines_path

app/views/disciplines/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @discipline.name
%p
  %b Description:
  = @discipline.description

%p
  %b Questions:
%table
  %tr
    %th Name
    %th Text
  - @discipline.questions.each do |question|
    %tr
      %td= link_to question.name, discipline_question_path(@discipline, question)
      %td= question.text
    %th= link_to 'New Question', new_discipline_question_path(@discipline)

= link_to 'Edit', edit_discipline_path(@discipline)
\|
= link_to 'Back', disciplines_path