config/routes.rb
WeightedDemocracy::Application.routes.draw do
  root :to => 'issues#index'

  resources :users

  resources :issues

  resources :disciplines do
    resources :questions
  end
    
  resources :questions do
    #/questions/1/answers maps to answers#index
    resources :answers
  end

  match '/login' => 'sessions#new', :as => 'login', :via => :get
  match '/login' => 'sessions#create', :as => 'login', :via => :post
  match '/logout' => 'sessions#destroy', :as => 'logout' 
end

app/models/issue.rb
class Issue < ActiveRecord::Base
  attr_accessible :description, :name, :discipline_id
  validates_presence_of :name
  validates_presence_of :description

  has_many :issue_disciplines
  has_many :disciplines, :through => :issue_disciplines

  #accepts_nested_attributes_for :issue_disciplines
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  # GET /issues
  # GET /issues.json
  def index
    @issues = Issue.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @issues }
    end
  end

  # GET /issues/1
  # GET /issues/1.json
  def show
    @issue = Issue.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @issue }
    end
  end

  # GET /issues/new
  # GET /issues/new.json
  def new
    @issue = Issue.new
    3.times { @issue.disciplines.build }

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @issue }
    end
  end

  # GET /issues/1/edit
  def edit
    @issue = Issue.find(params[:id])
  end

  # POST /issues
  # POST /issues.json
  def create
    @issue = Issue.new(params[:issue])

    respond_to do |format|
      if @issue.save
        format.html { redirect_to @issue, notice: 'Issue was successfully created.' }
        format.json { render json: @issue, status: :created, location: @issue }
      else
        format.html { render action: "new" }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /issues/1
  # PUT /issues/1.json
  def update
    @issue = Issue.find(params[:id])

    respond_to do |format|
      if @issue.update_attributes(params[:issue])
        format.html { redirect_to @issue, notice: 'Issue was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /issues/1
  # DELETE /issues/1.json
  def destroy
    @issue = Issue.find(params[:id])
    @issue.destroy

    respond_to do |format|
      format.html { redirect_to issues_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/views/issues/_form.html.haml
= form_for @issue do |f|
  - if @issue.errors.any?
    #error_explanation
      %h2= "#{pluralize(@issue.errors.count, "error")} prohibited this issue from being saved:"
      %ul
        - @issue.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_area :description
  .actions
    = f.submit 'Save'

app/views/issues/edit.html.haml
%h1 Editing issue

= render 'form'

= link_to 'Show', @issue
\|
= link_to 'Back', issues_path

app/views/issues/index.html.haml
%h1 Listing issues

%table
  %tr
    %th Name
    %th Description
    %th
    %th
    %th

  - @issues.each do |issue|
    %tr
      %td= link_to issue.name, issue
      %td= issue.description
      %td= link_to 'Edit', edit_issue_path(issue)
      %td= link_to 'Destroy', issue, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Issue', new_issue_path

app/views/issues/new.html.haml
%h1 New issue

= render 'form'

= link_to 'Back', issues_path

app/views/issues/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @issue.name
%p
  %b Description:
  = @issue.description

= link_to 'Edit', edit_issue_path(@issue)
\|
= link_to 'Back', issues_path