config/routes.rb
WeightedDemocracy::Application.routes.draw do
  root :to => 'issues#index'

  resources :users

  resources :issues

  resources :disciplines do
    resources :questions
  end
    
  resources :questions do
    #/questions/1/answers maps to answers#index
    resources :answers
  end

  match '/login' => 'sessions#new', :as => 'login', :via => :get
  match '/login' => 'sessions#create', :as => 'login', :via => :post
  match '/logout' => 'sessions#destroy', :as => 'logout' 
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  attr_accessible :text, :question_id
  validates_presence_of :text
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_filter :ensure_question

  def ensure_question
    @question = Question.find_by_id(params[:question_id])
    redirect_to questions_path if !@question
  end

  def index
    @answers = Answer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @answers }
    end
  end

  def show
    @answer = Answer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @answer }
    end
  end

  def new
    @answer = Answer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @answer }
    end
  end

  def edit
    @answer = Answer.find(params[:id])
  end

  def create
    @answer = Answer.new(params[:answer])

    respond_to do |format|
      if @answer.save
        format.html { redirect_to question_answer_path(@question, @answer), notice: 'Answer was successfully created.' }
        format.json { render json: @answer, status: :created, location: @answer }
      else
        format.html { render action: "new" }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @answer = Answer.find(params[:id])

    respond_to do |format|
      if @answer.update_attributes(params[:answer])
        format.html { redirect_to question_answer_path(@question, @answer), notice: 'Answer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @answer = Answer.find(params[:id])
    @answer.destroy

    respond_to do |format|
      format.html { redirect_to question_answers_path(@question.id) }
      format.json { head :no_content }
    end
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_form.html.haml
= form_for([@question, @answer]) do |f|
  - if @answer.errors.any?
    #error_explanation
      %h2= "#{pluralize(@answer.errors.count, "error")} prohibited this answer from being saved:"
      %ul
        - @answer.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :text
    = f.text_area :text
  .field
    = f.label :question_id
    = f.number_field :question_id
  .actions
    = f.submit 'Save'

app/views/answers/edit.html.haml
%h1 Editing answer

= render 'form'

= link_to 'Show', question_answer_path(@question, @answer)
\|
= link_to 'Back', question_answers_path(@question)

app/views/answers/index.html.haml
%h1 Listing answers

%table
  %tr
    %th Text
    %th Question
    %thr
    %th
    %th

  - @answers.each do |answer|
    %tr
      %td= link_to answer.text, edit_question_answer_path(@question, answer)
      %td= answer.question_id
      %td= link_to 'Show', question_answer_path(@question, answer)
      %td= link_to 'Destroy', question_answer_path(@question,answer), method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Answer', new_question_answer_path(@question)

app/views/answers/new.html.haml
%h1 New answer

= render 'form'

= link_to 'Back', question_answers_path(@question)

app/views/answers/show.html.haml
%p#notice= notice

%p
  %b Text:
  = @answer.text
%p
  %b Question:
  = @answer.question_id

= link_to 'Edit', edit_question_answer_path(@question, @answer)
\|
= link_to 'Back', question_path(@question)